version: '3.3'

services:
  web:
    container_name: developershop.web
    build: ./app
    command: gunicorn developershop.wsgi:application --bind 0.0.0.0:3762
    volumes:
      - ./app:/usr/src/app/
      - ./app/static:/usr/src/app/static
      - media_volume:/usr/src/app/media
    ports:
      - 3762:3762
    depends_on:
      - mysql
    env_file:
      - ./app/.env
    restart: always 
    networks:
      local_network:
        ipv4_address: 172.28.1.4

  nginx:
    container_name: developershop.proxy
    build: ./nginx
    volumes:
      - ./app/static:/usr/src/app/static
      - media_volume:/usr/src/app/media
    ports:
      - "80:80"
    depends_on:
      - web
    restart: always 
    networks:
      local_network:
        ipv4_address: 172.28.1.3

  mysql:
    image: mysql:latest
    container_name: developershop.mysql
    volumes:
      - db_data:/var/lib/mysql:rw
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
      MYSQL_DATABASE: 'db_ecommerce'
    ports:
      - "3306:3306"
    restart: always 
    networks:
      local_network:
        ipv4_address: 172.28.1.5

volumes:
  static_volume:
  media_volume:
  db_data:

networks:
  local_network:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16